runtime: nodejs10
env_variables: # test
  PORT: 80
  DATASTORE_NAMESPACE: "flatten_test"
  DATASTORE_KIND: "form-user"
# env_variables: # production
#  PORT: 80
#  DATASTORE_NAMESPACE: "flatten_production"
#  DATASTORE_KIND: "form-user"
