steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "src/api/backend.$PROJECT_ID.js", "src/api/backend.js"]
  - name: gcr.io/cloud-builders/npm:current
    entrypoint: "npm"
    args: ["install", "--production"]
  - name: gcr.io/cloud-builders/npm:current
    entrypoint: "npm"
    args: ["run", "build"]
  - name: gcr.io/$PROJECT_ID/firebase
    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']
