project_id_master: flatten-271620
project_id_staging: flatten-staging-271921
verification_email_template: d-7a10ff414f6d44b882eb9a4dadab16ad
staging:
  formio_project_url: formio-staging-6eoeawk53a-uc.a.run.app/testing-jrnkhofvnfhrvsv
  formio_api_secret: projects/233853318753/secrets/formio-api-secret/versions/latest
  sendgrid_secret: projects/233853318753/secrets/sendgrid-api-key/versions/latest
  formio_jwt_secret: projects/233853318753/secrets/formio-jwt-secret/versions/latest
  frontend_url: localhost:3000