export default {
  SET_FOLLOW_UP_ID: "SET_FOLLOWUP_ID",
  SET_LOCATION: "SET_LOCATION",
  SET_FORMIO_CONTENT: "SET_FORMIO_CONTENT",
  RESTART_SURVEY: "RESTART_SURVEY",
  NOTIFY_CONSENT_GIVEN: "NOTIFY_CONSENT_GIVEN",
  SET_START_TIME: "SET_START_TIME",
  NOTIFY_FOLLOW_UP_ID_RECORDED: "NOTIFY_FOLLOW_UP_ID_RECORDED",
};
