export default {
  SET_FOLLOW_UP_ID: "SET_FOLLOWUP_ID",
  SET_LOCATION: "SET_LOCATION",
  SET_LOCATION_TIME: "SET_LOCATION_TIME",
  SET_FORMIO_CONTENT: "SET_FORMIO_CONTENT",
  RESTART_SURVEY: "RESTART_SURVEY",
  NOTIFY_CONSENT_GIVEN: "NOTIFY_CONSENT_GIVEN",
  SET_CONSENT_TIME: "SET_CONSENT_TIME",
  NOTIFY_STARTED: "NOTIFY_STARTED",
  SET_START_TIME: "SET_START_TIME",
  NOTIFY_FOLLOW_UP_ID_RECORDED: "NOTIFY_FOLLOW_UP_ID_RECORDED",
  NOTIFY_COMPLETED_SURVEY: "NOTIFY_COMPLETED_SURVEY",
};
