steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - prod-to-analytic-data-pipeline
      - --region=eure
      - --source=./cloud-function-analytics.js
      - --timeout=500
      - --trigger-topic=somalia-prod-to-analytics
      - --entry-point=main
      - --runtime nodejs12
      - --service-account=prod-to-analytics-pipeline@somalia-prod.iam.gserviceaccount.com
      - --vpc-connector=analytics-data-pipeline